version: "3"
services:
  db:
    image: mysql
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:5.0.1
  sidekiq:
    build: .
    env_file: .env
    command: sidekiq -C config/sidekiq.yml -L log/sidekiq.log
    volumes:
      - .:/myapp
    depends_on:
      - db
  web:
    build: .
    env_file: .env
    entrypoint: entrypoint.sh
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
    db_data:
